import { Container, Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Agdasima, Dancing_Script, Dosis } from 'next/font/google'
import AppFooter from './components/appFooter'
import AppHeader from './components/appHeader'
import './globals.css'
import './theme-config.css'

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// })

const dancing = Dancing_Script({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-dancing',
  display: 'swap',
})
const dosis = Dosis({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-dancing',
  display: 'swap',
})

const agdasima = Agdasima({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-agdasima',
})

export const metadata: Metadata = {
  title: 'NextNazs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon-32x32.png" sizes="any" />
      <body className={`${dosis.className} antialiased flex flex-col `}>
        <Theme accentColor="violet" className="mb-auto flex flex-col ">
          <AppHeader />
          <main className="grow flex p-5">
            <Container>{children}</Container>
          </main>
          <AppFooter />
        </Theme>
      </body>
    </html>
  )
}
